import baseConfig from "@cherrio/config/eslint/base.js";

// ponder-env.d.ts is generated by `ponder codegen` and must not be edited.
export default [{ ignores: ["ponder-env.d.ts"] }, ...baseConfig];
