#!/usr/bin/env bash
# Export ABIs for PlatformConfig, CampaignFactory and Campaign to abis/*.json
# and generate abis/index.ts for viem consumption (inlined, no JSON imports).
# Run from packages/contracts: pnpm run export-abis
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT"

forge build --silent

CONTRACTS=(PlatformConfig CampaignFactory Campaign)

for contract in "${CONTRACTS[@]}"; do
  python3 -c "import sys,json; print(json.dumps(json.load(sys.stdin)['abi'], indent=2))" \
    < "out/${contract}.sol/${contract}.json" > "abis/${contract}.json"
  echo "Exported abis/${contract}.json"
done

# Generate index.ts with inlined ABI literals (no JSON imports needed)
INDEX="abis/index.ts"
{
  echo "// Auto-generated by export.sh — do not edit manually"
  echo "// eslint-disable-next-line @typescript-eslint/no-explicit-any"
  echo ""
  for contract in "${CONTRACTS[@]}"; do
    echo "export const ${contract}Abi = $(python3 -c "import sys,json; print(json.dumps(json.load(sys.stdin)['abi']))" < "out/${contract}.sol/${contract}.json") as const;"
    echo ""
  done
} > "$INDEX"

echo "Generated $INDEX"
echo "ABI export complete."
