import { randomBytes } from "node:crypto";
import { and, eq } from "drizzle-orm";
import { auditLog, campaignMedia, campaigns, type Database } from "@cherrio/db";
import { MAX_IMAGE_BYTES, processCoverImage } from "@/lib/media/image";
import { publicMediaUrl, putPublicImage } from "@/lib/media/public-store";
import { demoCampaignsAllowed } from "./create";
import { DEMO_POOL } from "./pool";

// ADR-052 §4 (TASK-038b): cover images for demo campaigns, generated by fal.ai
// (Nano Banana Pro) with the server secret FAL_KEY. fal's queue API is used —
// submit, then poll — so no request to CHERR.IO waits for the model and runs
// into kamal-proxy's 30-second response timeout. The key is only ever sent to
// queue.fal.run and never logged.

export const FAL_MODEL = "fal-ai/nano-banana-pro";
export const FAL_QUEUE = `https://queue.fal.run/${FAL_MODEL}`;
const REQUEST_ID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export type DemoCoverRefusal = "not_allowed" | "not_configured" | "not_found" | "generation_failed" | "bad_request";
export class DemoCoverError extends Error {
  constructor(public readonly code: DemoCoverRefusal) {
    super(code);
    this.name = "DemoCoverError";
  }
}

export interface DemoCoverOptions {
  apiKey?: string;
  appEnv?: string;
  fetchImpl?: typeof fetch;
  put?: (key: string, webp: Buffer) => Promise<void>;
}

/** The photo brief for one pool entry: documentary look, no text, no real or famous people. */
export function demoCoverPrompt(scene: string): string {
  return (
    `Documentary-style colour photograph, natural light, realistic, 4:3: ${scene}. ` +
    "No text, no letters, no logos, no watermarks, no brand names. " +
    "If people appear they are ordinary, not famous, seen from a distance or from behind; no identifiable faces."
  );
}

/** The pool entry a demo campaign was made from ("Title (2)" → "Title"). */
export function sceneForTitle(title: string): string {
  const base = title.replace(/ \(\d+\)$/, "");
  return DEMO_POOL.find((s) => s.title === base)?.scene ?? `a small charity project: ${base}`;
}

function setup(options: DemoCoverOptions) {
  if (!demoCampaignsAllowed(options.appEnv ?? process.env.APP_ENV)) throw new DemoCoverError("not_allowed");
  const apiKey = options.apiKey ?? process.env.FAL_KEY;
  if (!apiKey) throw new DemoCoverError("not_configured");
  return { apiKey, fetchImpl: options.fetchImpl ?? fetch, put: options.put ?? putPublicImage };
}

async function loadDemo(db: Database, campaignId: string) {
  const [row] = await db
    .select({ id: campaigns.id, title: campaigns.title, isDemo: campaigns.isDemo })
    .from(campaigns)
    .where(eq(campaigns.id, campaignId))
    .limit(1);
  if (!row || !row.isDemo) throw new DemoCoverError("not_found");
  const [cover] = await db
    .select({ cid: campaignMedia.cid })
    .from(campaignMedia)
    .where(and(eq(campaignMedia.campaignId, campaignId), eq(campaignMedia.kind, "COVER")))
    .limit(1);
  return { ...row, coverCid: cover?.cid ?? null };
}

export type DemoCoverResult = { status: "done"; url: string } | { status: "pending"; requestId: string };

/** Starts generating a cover. A demo campaign that already has one returns it (no second paid image). */
export async function startDemoCover(db: Database, campaignId: string, options: DemoCoverOptions = {}): Promise<DemoCoverResult> {
  const { apiKey, fetchImpl } = setup(options);
  const campaign = await loadDemo(db, campaignId);
  if (campaign.coverCid) return { status: "done", url: publicMediaUrl(campaign.coverCid) };

  const res = await fetchImpl(FAL_QUEUE, {
    method: "POST",
    headers: { Authorization: `Key ${apiKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      prompt: demoCoverPrompt(sceneForTitle(campaign.title)),
      num_images: 1,
      aspect_ratio: "4:3",
      resolution: "1K",
      output_format: "jpeg",
    }),
    signal: AbortSignal.timeout(20_000),
  }).catch(() => null);
  const body = res?.ok ? ((await res.json().catch(() => null)) as { request_id?: unknown } | null) : null;
  if (!res?.ok || typeof body?.request_id !== "string" || !REQUEST_ID_RE.test(body.request_id)) {
    console.error("[demo.cover] fal submit failed:", res ? res.status : "no response");
    throw new DemoCoverError("generation_failed");
  }
  return { status: "pending", requestId: body.request_id };
}

/**
 * Checks a generation. While fal is working: pending. When it is done: the
 * image is downloaded, re-encoded to WebP without metadata (same path as an
 * uploaded cover) and stored as the campaign's COVER.
 */
export async function finishDemoCover(
  db: Database,
  adminId: string,
  campaignId: string,
  requestId: string,
  options: DemoCoverOptions = {}
): Promise<DemoCoverResult> {
  if (!REQUEST_ID_RE.test(requestId)) throw new DemoCoverError("bad_request");
  const { apiKey, fetchImpl, put } = setup(options);
  const campaign = await loadDemo(db, campaignId);
  if (campaign.coverCid) return { status: "done", url: publicMediaUrl(campaign.coverCid) };

  const auth = { Authorization: `Key ${apiKey}` };
  const statusRes = await fetchImpl(`${FAL_QUEUE}/requests/${requestId}/status`, { headers: auth, signal: AbortSignal.timeout(15_000) }).catch(() => null);
  const status = statusRes?.ok ? ((await statusRes.json().catch(() => null)) as { status?: string } | null)?.status : undefined;
  if (status === "IN_QUEUE" || status === "IN_PROGRESS") return { status: "pending", requestId };
  if (status !== "COMPLETED") {
    console.error("[demo.cover] fal status failed:", statusRes ? statusRes.status : "no response", status ?? "");
    throw new DemoCoverError("generation_failed");
  }

  const resultRes = await fetchImpl(`${FAL_QUEUE}/requests/${requestId}`, { headers: auth, signal: AbortSignal.timeout(15_000) }).catch(() => null);
  const result = resultRes?.ok ? ((await resultRes.json().catch(() => null)) as { images?: { url?: unknown }[] } | null) : null;
  const imageUrl = result?.images?.[0]?.url;
  if (typeof imageUrl !== "string" || !imageUrl.startsWith("https://")) {
    console.error("[demo.cover] fal result without an https image:", resultRes ? resultRes.status : "no response");
    throw new DemoCoverError("generation_failed");
  }
  // The image URL is fal's CDN; no credentials are sent there.
  const imageRes = await fetchImpl(imageUrl, { signal: AbortSignal.timeout(30_000) }).catch(() => null);
  const length = Number(imageRes?.headers.get("content-length") ?? "0");
  if (!imageRes?.ok || length > MAX_IMAGE_BYTES) throw new DemoCoverError("generation_failed");
  let webp: Buffer;
  try {
    webp = await processCoverImage(Buffer.from(await imageRes.arrayBuffer()));
  } catch {
    throw new DemoCoverError("generation_failed");
  }

  const key = `campaigns/${campaignId}/${randomBytes(12).toString("hex")}.webp`;
  await put(key, webp);
  const stored = await db.transaction(async (tx) => {
    const [existing] = await tx
      .select({ cid: campaignMedia.cid })
      .from(campaignMedia)
      .where(and(eq(campaignMedia.campaignId, campaignId), eq(campaignMedia.kind, "COVER")))
      .limit(1);
    if (existing) return existing.cid; // a parallel check stored one first; ours stays an orphan for the sweep
    await tx.insert(campaignMedia).values({ campaignId, kind: "COVER", storage: "HETZNER_PUBLIC", cid: key, createdBy: adminId });
    await tx.insert(auditLog).values({
      actorUserId: adminId,
      action: "demo.cover_generated",
      entityType: "campaign",
      entityId: campaignId,
      data: { model: FAL_MODEL, requestId, key },
    });
    return key;
  });
  return { status: "done", url: publicMediaUrl(stored) };
}
